// Brand font system — EMBEDDED in the bundle (fonts.data.ts, generated by
// tools/getfonts.py), so rendering makes no font network requests at all:
// - Google's runtime CDN fetch fails behind the restricted egress proxy (the render
//   browser can't validate the proxy CA);
// - serving woff2 via staticFile still has every parallel render tab fetch them at
//   startup, which can starve one tab past the delayRender timeout.
// Faces load from memory. Variable fonts cover their weight range with one face.
// Family names are unchanged, so every shot keeps working.
import { continueRender, delayRender } from 'remotion';
import { FONT_FACES } from './fonts.data';

const bytes = (b64: string) => Uint8Array.from(atob(b64), (c) => c.charCodeAt(0));

if (typeof document !== 'undefined' && typeof FontFace !== 'undefined') {
  // A FontFace built from in-memory bytes is decoded synchronously by Chromium (status is
  // already 'loaded'), so it is registered before the first paint and nothing needs to wait.
  // Only a face that is genuinely still loading gets a delayRender. (Awaiting load() on every
  // face unconditionally left a handle that never cleared in some render pages.)
  const faces = FONT_FACES.map((f) => new FontFace(f.family, bytes(f.woff2), { weight: f.weight, style: 'normal' }));
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  faces.forEach((ff) => (document.fonts as any).add(ff));
  const pending = faces.filter((ff) => ff.status !== 'loaded');
  if (pending.length > 0) {
    const handle = delayRender(`embedded fonts (${pending.length} still loading)`, { timeoutInMilliseconds: 60000 });
    Promise.allSettled(pending.map((ff) => ff.loaded)).then(() => continueRender(handle));
  }
}

export const FONT_DISPLAY = 'Space Grotesk';
export const FONT_BODY = 'Inter';
export const FONT_MONO = 'JetBrains Mono';
// serif for the Claude Code wordmark clone (close match to the app's serif)
export const FONT_SERIF = 'Spectral';
// heavy editorial serif for the vox collage engine's headlines
export const FONT_EDITORIAL = 'Source Serif 4';
