#!/usr/bin/env python3
"""Fetch the brand fonts (latin subset, woff2) and EMBED them in the Remotion bundle as
remotion/src/fonts.data.ts, so rendering needs no font network requests at all.

Why embedded, not served: @remotion/google-fonts fetches from Google's CDN at render time
(fails behind a restricted egress proxy — the render browser can't validate the proxy CA),
and serving local woff2 via staticFile() still makes every parallel render tab fetch them
from the bundle server at startup, which can starve one tab past the delayRender timeout.
Bytes in the bundle load from memory: no fetch, nothing to wait on.

Google serves variable fonts for most families (one file covers every weight), so faces
are de-duplicated by file and registered with a weight RANGE (e.g. "400 600").

Honours HTTPS_PROXY and SSL_CERT_FILE (urllib reads both). Run from the repo root:
    python tools/getfonts.py
Re-run whenever a family or weight changes in FAMILIES (keep src/fonts.ts exports in sync).
"""
import base64
import os
import re
import urllib.request

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "remotion", "src", "fonts.data.ts")
UA = ("Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) "
      "Chrome/120.0.0.0 Safari/537.36")

# family (Google name) -> weights actually used. Mirror src/fonts.ts.
FAMILIES = {
    "Space Grotesk": [500, 600, 700],
    "Inter": [400, 500, 600],
    "JetBrains Mono": [400, 500, 700],
    "Spectral": [500, 600],
    "Source Serif 4": [600, 700, 900],
}


def get(url, binary=False):
    req = urllib.request.Request(url, headers={"User-Agent": UA})
    with urllib.request.urlopen(req, timeout=60) as r:
        return r.read() if binary else r.read().decode("utf-8")


def main():
    fam_q = "&".join(
        "family=" + f.replace(" ", "+") + ":wght@" + ";".join(str(w) for w in ws)
        for f, ws in FAMILIES.items()
    )
    css = get("https://fonts.googleapis.com/css2?" + fam_q + "&display=block")
    faces = {}  # (family, url) -> [weights]
    # each /* subset */ comment applies to the following @font-face block; keep latin.
    for subset, body in re.findall(r"/\*\s*([\w-]+)\s*\*/\s*@font-face\s*\{([^}]*)\}", css):
        if subset != "latin":
            continue
        fam = re.search(r"font-family:\s*'([^']+)'", body).group(1)
        wght = int(re.search(r"font-weight:\s*(\d+)", body).group(1))
        url = re.search(r"url\((https://[^)]+\.woff2)\)", body).group(1)
        faces.setdefault((fam, url), []).append(wght)

    lines = [
        "// AUTO-GENERATED by tools/getfonts.py — do not hand-edit. Latin-subset woff2, base64.",
        "// Embedded so renders never fetch fonts (see fonts.ts / tools/getfonts.py).",
        "export const FONT_FACES: { family: string; weight: string; woff2: string }[] = [",
    ]
    total = 0
    for (fam, url), ws in sorted(faces.items(), key=lambda kv: (kv[0][0], min(kv[1]))):
        data = get(url, binary=True)
        total += len(data)
        weight = str(ws[0]) if len(ws) == 1 else f"{min(ws)} {max(ws)}"
        lines.append(f"  {{ family: '{fam}', weight: '{weight}', woff2: '{base64.b64encode(data).decode()}' }},")
        print(f"  {fam:15} {weight:9} {len(data)/1024:6.1f} KB")
    lines += ["];", ""]
    with open(OUT, "w") as fh:
        fh.write("\n".join(lines))
    print(f"wrote {len(faces)} faces ({total/1024:.0f} KB woff2) -> {os.path.relpath(OUT, ROOT)}")


if __name__ == "__main__":
    main()
